In [14]:
import numpy as np
np.__version__

#help(np.array)

#construindo um array com NumPy
primeiroVetor = np.array([0, 1, 2, 3, 4, 5])
print(primeiroVetor)
type(primeiroVetor)

# semelhante ao range() do python
# args: start | stop | step
vetorArange = np.arange(0, 5, .5)

print(vetorArange)

# cria um array preenchido com zeros
print(np.zeros(10))

#cria um array com o valor 1 nas posições em diagonal e 0 no restante
z = np.eye(3)
print(z)

#Cria uma diagonal com os valores passados como argumento
d = np.diag(np.array([1,2,3,4]))
print(d)

#array com valores complexos
c = np.array([1+2j, 3+4j, 5+6*1j])
print(c)

arrayBoleano = np.array([True, False, True, True])
print(arrayBoleano)


arrayStrings = np.array(['SQL', 'Python', 'R'])
print(arrayStrings)

print(np.linspace(0, 10))


[0 1 2 3 4 5]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[1.+2.j 3.+4.j 5.+6.j]
[ True False  True  True]
['SQL' 'Python' 'R']
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
