In [14]:
import numpy as np
#Matriz é um array bi-dimensional
matriz = np.array([[1,2,3,4], [1,5,7, 8]])
print(matriz)
print(matriz.shape)

matrizOnes = np.ones((2,3))
print(matrizOnes)

#Convertendo uma lista de listas para uma matriz bidimensional
lista = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]
matrizListaListas = np.matrix(lista)
print(matrizListaListas)

print(matrizListaListas.size)

[[1 2 3 4]
 [1 5 7 8]]
(2, 4)
[[1. 1. 1.]
 [1. 1. 1.]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
