In [18]:
import numpy as np

a = np.diag(np.arange(3))

print(a)

print(a[1,1])

print(a[1])

b = np.arange(10)
print(b)

#start:stop:step
print(b[2:9:3])

primeiroArray = np.array([1,2,3])
segundoArray = np.array([3,2,1])

print(np.array_equal(primeiroArray, segundoArray))


C = b.flatten()
print(C)


v = np.array([1,2,3])
v[:, np.newaxis], v[:, np.newaxis].shape, v[np.newaxis,:].shape


#Repetiçao dos elementos do array
np.repeat(v, 3)

[[0 0 0]
 [0 1 0]
 [0 0 2]]
1
[0 1 0]
[0 1 2 3 4 5 6 7 8 9]
[2 5 8]
False
[0 1 2 3 4 5 6 7 8 9]


array([1, 1, 1, 2, 2, 2, 3, 3, 3])